import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';

// The logo's three curves live in three places for reasons that can't be avoided:
//   1. public/brand/kairo-mark.svg      — the canonical asset (regenerated by scripts/brand/)
//   2. src/components/KairoMark.tsx     — inlined; Vite runs with base './' across four hash-routed
//                                         WebViews, so an absolute /brand URL isn't reliable
//   3. server/src/auth/routes.ts        — inlined; that page is served from the API host and can't
//                                         reach the desktop bundle at all
// Nothing at build time ties them together, so this test does: edit one, edit all three.

const root = resolve(__dirname, '..');
const read = (p: string) => readFileSync(resolve(root, p), 'utf8');

/** Every `d="…"` in source order. The mark is body, then face, then eyes. */
function paths(source: string): string[] {
  return [...source.matchAll(/\bd="([^"]+)"/g)].map((m) => m[1]);
}

/** The component stores each path in a const instead of an attribute. */
function componentPaths(source: string): string[] {
  return ['BODY', 'FACE', 'EYES'].map((name) => {
    const m = source.match(new RegExp(`const ${name} =\\s*\\n?\\s*'([^']+)'`));
    if (!m) throw new Error(`KairoMark.tsx: no ${name} path found`);
    return m[1];
  });
}

describe('brand mark', () => {
  const canonical = paths(read('public/brand/kairo-mark.svg'));

  test('the canonical SVG has the three expected paths', () => {
    expect(canonical).toHaveLength(3);
    canonical.forEach((d) => expect(d.startsWith('M')).toBe(true));
  });

  test('the React component is in sync with the canonical SVG', () => {
    expect(componentPaths(read('src/components/KairoMark.tsx'))).toEqual(canonical);
  });

  test("the OAuth success page's inlined mark is in sync", () => {
    // That file also contains the success tick, so match only the mark's own paths.
    const inMark = paths(read('server/src/auth/routes.ts')).filter((d) => canonical.includes(d));
    expect(inMark).toEqual(canonical);
  });
});
